# Generated by Django 3.2.4 on 2021-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interval', models.IntegerField()),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('upTime', models.IntegerField(default=0)),
                ('downTime', models.IntegerField(default=0)),
            ],
        ),
    ]
