# Generated by Django 3.2.4 on 2021-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0003_auto_20210607_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
