# Generated by Django 3.2.4 on 2021-06-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0004_alter_monitordetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitorCountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=20)),
                ('monitorDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemonitor.monitordetails')),
            ],
        ),
    ]
