# Generated by Django 3.2.4 on 2021-06-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0006_auto_20210608_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordetails',
            name='SSLEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='sslCountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSSL', models.BooleanField(default=True)),
                ('SSLCheckTime', models.DateTimeField(blank=True, null=True)),
                ('SSLDetails', models.TextField()),
                ('monitorDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemonitor.monitordetails')),
            ],
        ),
    ]
