# Generated by Django 3.2.4 on 2021-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0007_auto_20210611_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordetails',
            name='SSLInterval',
            field=models.IntegerField(default=0),
        ),
    ]
